import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1777700973108 implements MigrationInterface {
    name = 'Migration1777700973108'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" text NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "is_revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_expires_at" ON "refresh_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_user_id" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "billing_email" text, "plan" character varying NOT NULL DEFAULT 'free', "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "suspended_at" TIMESTAMP WITH TIME ZONE, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "organizations_slug_unique_active" ON "organizations" ("slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" text NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d090ad82a0e97ce764c06c7b312" UNIQUE ("slug"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "permissions_slug_unique_active" ON "permissions" ("slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "name" text NOT NULL, "slug" text NOT NULL, "description" text, "scope" character varying NOT NULL DEFAULT 'organization', "level" integer NOT NULL DEFAULT '100', "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_system_slug_unique_active" ON "roles" ("slug") WHERE organization_id IS NULL AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_organization_slug_unique_active" ON "roles" ("organization_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'active', "invited_at" TIMESTAMP WITH TIME ZONE, "joined_at" TIMESTAMP WITH TIME ZONE, "suspended_at" TIMESTAMP WITH TIME ZONE, "removed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "organization_id" uuid, "user_id" uuid, "role_id" uuid, "invited_by" uuid, CONSTRAINT "PK_25d28bd932097a9e90495ede7b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "memberships_status_idx" ON "memberships" ("status") `);
        await queryRunner.query(`CREATE INDEX "memberships_role_id_idx" ON "memberships" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "memberships_user_id_idx" ON "memberships" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "memberships_organization_id_idx" ON "memberships" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "memberships_organization_user_unique_active" ON "memberships" ("organization_id", "user_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "name" text, "lastname" text, "password_hash" text, "avatar_url" text, "status" character varying NOT NULL DEFAULT 'pending', "email_verified_at" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_email_unique_active" ON "users" ("email") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'active', "latest_version" text, "settings" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "archived_at" TIMESTAMP WITH TIME ZONE, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "organization_id" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "projects_status_idx" ON "projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "projects_organization_id_idx" ON "projects" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "projects_organization_slug_unique_active" ON "projects" ("organization_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "environments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "description" text, "type" character varying NOT NULL DEFAULT 'development', "is_production" boolean NOT NULL DEFAULT false, "base_version" text, "latest_version" text, "settings" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, CONSTRAINT "PK_ec32d12469ec3c2f2f20c4f5e71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "environments_is_production_idx" ON "environments" ("is_production") `);
        await queryRunner.query(`CREATE INDEX "environments_type_idx" ON "environments" ("type") `);
        await queryRunner.query(`CREATE INDEX "environments_project_id_idx" ON "environments" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "environments_one_production_per_project" ON "environments" ("project_id") WHERE is_production = true AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "environments_project_slug_unique_active" ON "environments" ("project_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "path" text NOT NULL, "type" character varying NOT NULL, "token_kind" character varying NOT NULL, "value" jsonb NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "deprecated_at" TIMESTAMP WITH TIME ZONE, "archived_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "environment_id" uuid, CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "tokens_status_idx" ON "tokens" ("status") `);
        await queryRunner.query(`CREATE INDEX "tokens_token_kind_idx" ON "tokens" ("token_kind") `);
        await queryRunner.query(`CREATE INDEX "tokens_type_idx" ON "tokens" ("type") `);
        await queryRunner.query(`CREATE INDEX "tokens_environment_id_idx" ON "tokens" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "tokens_project_id_idx" ON "tokens" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tokens_environment_path_unique_active" ON "tokens" ("environment_id", "path") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "token_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" text NOT NULL, "format" character varying NOT NULL DEFAULT 'json', "storage_url" text NOT NULL, "checksum" text NOT NULL, "status" character varying NOT NULL DEFAULT 'created', "published_at" TIMESTAMP WITH TIME ZONE, "deprecated_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "environment_id" uuid, "created_by" uuid, CONSTRAINT "PK_a5fdb993dcdf6b17ff30013780f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "token_snapshots_created_by_idx" ON "token_snapshots" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "token_snapshots_status_idx" ON "token_snapshots" ("status") `);
        await queryRunner.query(`CREATE INDEX "token_snapshots_version_idx" ON "token_snapshots" ("version") `);
        await queryRunner.query(`CREATE INDEX "token_snapshots_environment_id_idx" ON "token_snapshots" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "token_snapshots_project_id_idx" ON "token_snapshots" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "token_snapshots_environment_version_unique_active" ON "token_snapshots" ("environment_id", "version") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "token_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" text NOT NULL, "name" text, "changelog" text, "status" character varying NOT NULL DEFAULT 'published', "published_at" TIMESTAMP WITH TIME ZONE, "deprecated_at" TIMESTAMP WITH TIME ZONE, "rolled_back_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "environment_id" uuid, "snapshot_id" uuid, "published_by" uuid, CONSTRAINT "PK_40e9fa1ecbd2fc7848d6ef1c61e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "token_versions_published_at_idx" ON "token_versions" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "token_versions_published_by_idx" ON "token_versions" ("published_by") `);
        await queryRunner.query(`CREATE INDEX "token_versions_status_idx" ON "token_versions" ("status") `);
        await queryRunner.query(`CREATE INDEX "token_versions_snapshot_id_idx" ON "token_versions" ("snapshot_id") `);
        await queryRunner.query(`CREATE INDEX "token_versions_environment_id_idx" ON "token_versions" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "token_versions_project_id_idx" ON "token_versions" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "token_versions_snapshot_unique_active" ON "token_versions" ("snapshot_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "token_versions_environment_version_unique_active" ON "token_versions" ("environment_id", "version") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "token_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference_path" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "token_id" uuid, "referenced_token_id" uuid, CONSTRAINT "PK_ba1043ce49c8a8f08cd48b8b47d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "token_references_referenced_token_id_idx" ON "token_references" ("referenced_token_id") `);
        await queryRunner.query(`CREATE INDEX "token_references_token_id_idx" ON "token_references" ("token_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "token_references_unique_active" ON "token_references" ("token_id", "referenced_token_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "themes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "description" text, "is_default" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "archived_at" TIMESTAMP WITH TIME ZONE, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "environment_id" uuid, "extends_theme_id" uuid, CONSTRAINT "PK_ddbeaab913c18682e5c88155592" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "themes_status_idx" ON "themes" ("status") `);
        await queryRunner.query(`CREATE INDEX "themes_extends_theme_id_idx" ON "themes" ("extends_theme_id") `);
        await queryRunner.query(`CREATE INDEX "themes_environment_id_idx" ON "themes" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "themes_project_id_idx" ON "themes" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "themes_one_default_per_environment" ON "themes" ("environment_id") WHERE is_default = true AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "themes_environment_slug_unique_active" ON "themes" ("environment_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "theme_overrides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" jsonb NOT NULL, "description" text, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "theme_id" uuid, "token_id" uuid, CONSTRAINT "PK_99900724b0e7fdc1267646793ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "theme_overrides_token_id_idx" ON "theme_overrides" ("token_id") `);
        await queryRunner.query(`CREATE INDEX "theme_overrides_theme_id_idx" ON "theme_overrides" ("theme_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "theme_overrides_theme_token_unique_active" ON "theme_overrides" ("theme_id", "token_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "team_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "joined_at" TIMESTAMP WITH TIME ZONE, "removed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "team_id" uuid, "membership_id" uuid, "role_id" uuid, CONSTRAINT "PK_053171f713ec8a2f09ed58f08f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_memberships_team_membership_unique_active" ON "team_memberships" ("team_id", "membership_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "team_memberships_status_idx" ON "team_memberships" ("status") `);
        await queryRunner.query(`CREATE INDEX "team_memberships_role_id_idx" ON "team_memberships" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "team_memberships_membership_id_idx" ON "team_memberships" ("membership_id") `);
        await queryRunner.query(`CREATE INDEX "team_memberships_team_id_idx" ON "team_memberships" ("team_id") `);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "organization_id" uuid, CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "teams_organization_slug_unique_active" ON "teams" ("organization_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "teams_status_idx" ON "teams" ("status") `);
        await queryRunner.query(`CREATE INDEX "teams_organization_id_idx" ON "teams" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "apps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "description" text, "platform" character varying NOT NULL, "framework" character varying NOT NULL, "repo_url" text, "current_version" text, "status" character varying NOT NULL DEFAULT 'active', "sync_status" character varying NOT NULL DEFAULT 'never_synced', "last_sync_at" TIMESTAMP WITH TIME ZONE, "settings" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "paused_at" TIMESTAMP WITH TIME ZONE, "archived_at" TIMESTAMP WITH TIME ZONE, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "organization_id" uuid, "project_id" uuid, "environment_id" uuid, CONSTRAINT "PK_c5121fda0f8268f1f7f84134e19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "apps_sync_status_idx" ON "apps" ("sync_status") `);
        await queryRunner.query(`CREATE INDEX "apps_status_idx" ON "apps" ("status") `);
        await queryRunner.query(`CREATE INDEX "apps_framework_idx" ON "apps" ("framework") `);
        await queryRunner.query(`CREATE INDEX "apps_platform_idx" ON "apps" ("platform") `);
        await queryRunner.query(`CREATE INDEX "apps_environment_id_idx" ON "apps" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "apps_project_id_idx" ON "apps" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "apps_organization_id_idx" ON "apps" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "apps_project_environment_slug_unique_active" ON "apps" ("project_id", "environment_id", "slug") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "prefix" text NOT NULL, "key_hash" text NOT NULL, "scopes" jsonb NOT NULL DEFAULT '[]', "status" character varying NOT NULL DEFAULT 'active', "last_used_at" TIMESTAMP WITH TIME ZONE, "last_used_ip" inet, "last_used_user_agent" text, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "revoked_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "organization_id" uuid, "user_id" uuid, "role_id" uuid, "created_by" uuid, CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "api_keys_last_used_at_idx" ON "api_keys" ("last_used_at") `);
        await queryRunner.query(`CREATE INDEX "api_keys_created_by_idx" ON "api_keys" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "api_keys_prefix_idx" ON "api_keys" ("prefix") `);
        await queryRunner.query(`CREATE INDEX "api_keys_status_idx" ON "api_keys" ("status") `);
        await queryRunner.query(`CREATE INDEX "api_keys_role_id_idx" ON "api_keys" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "api_keys_user_id_idx" ON "api_keys" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "api_keys_organization_id_idx" ON "api_keys" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "api_keys_key_hash_unique_active" ON "api_keys" ("key_hash") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "sync_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" text, "cli_version" text, "status" character varying NOT NULL DEFAULT 'pending', "trigger_source" character varying NOT NULL DEFAULT 'cli', "tokens_synced" integer NOT NULL DEFAULT '0', "files_written" integer NOT NULL DEFAULT '0', "duration_ms" integer, "error_code" text, "error_message" text, "metadata" jsonb NOT NULL DEFAULT '{}', "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "app_id" uuid, "project_id" uuid, "environment_id" uuid, "triggered_by" uuid, "api_key_id" uuid, CONSTRAINT "PK_7f83b5e08d1e175b0d504531b05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "sync_reports_created_at_idx" ON "sync_reports" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_api_key_id_idx" ON "sync_reports" ("api_key_id") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_triggered_by_idx" ON "sync_reports" ("triggered_by") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_trigger_source_idx" ON "sync_reports" ("trigger_source") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_status_idx" ON "sync_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_environment_id_idx" ON "sync_reports" ("environment_id") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_project_id_idx" ON "sync_reports" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "sync_reports_app_id_idx" ON "sync_reports" ("app_id") `);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "member_type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "membership_id" uuid, "team_id" uuid, "role_id" uuid, CONSTRAINT "project_members_exactly_one_member" CHECK ((("membership_id" IS NOT NULL AND "team_id" IS NULL AND "member_type" = 'user') OR ("membership_id" IS NULL AND "team_id" IS NOT NULL AND "member_type" = 'team'))), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "project_members_project_team_unique_active" ON "project_members" ("project_id", "team_id") WHERE team_id IS NOT NULL AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "project_members_project_membership_unique_active" ON "project_members" ("project_id", "membership_id") WHERE membership_id IS NOT NULL AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "project_members_status_idx" ON "project_members" ("status") `);
        await queryRunner.query(`CREATE INDEX "project_members_member_type_idx" ON "project_members" ("member_type") `);
        await queryRunner.query(`CREATE INDEX "project_members_role_id_idx" ON "project_members" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "project_members_team_id_idx" ON "project_members" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "project_members_membership_id_idx" ON "project_members" ("membership_id") `);
        await queryRunner.query(`CREATE INDEX "project_members_project_id_idx" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "merge_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" text NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'open', "review_status" character varying NOT NULL DEFAULT 'pending', "changelog" text, "source_version" text, "target_version" text, "checks" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "merged_at" TIMESTAMP WITH TIME ZONE, "closed_at" TIMESTAMP WITH TIME ZONE, "conflict_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, "project_id" uuid, "source_environment_id" uuid, "target_environment_id" uuid, "created_by" uuid, "merged_by" uuid, "closed_by" uuid, CONSTRAINT "PK_b6c55799f59a81ea08fb03dedd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "merge_requests_created_at_idx" ON "merge_requests" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_merged_by_idx" ON "merge_requests" ("merged_by") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_created_by_idx" ON "merge_requests" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_review_status_idx" ON "merge_requests" ("review_status") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_status_idx" ON "merge_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_target_environment_id_idx" ON "merge_requests" ("target_environment_id") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_source_environment_id_idx" ON "merge_requests" ("source_environment_id") `);
        await queryRunner.query(`CREATE INDEX "merge_requests_project_id_idx" ON "merge_requests" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "merge_requests_open_unique_active" ON "merge_requests" ("project_id", "source_environment_id", "target_environment_id") WHERE status IN ('open', 'draft', 'conflict') AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "merge_conflicts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token_path" text NOT NULL, "conflict_type" character varying NOT NULL DEFAULT 'value_mismatch', "source_value" jsonb, "target_value" jsonb, "resolved_value" jsonb, "status" character varying NOT NULL DEFAULT 'open', "resolved_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "merge_request_id" uuid, "token_id" uuid, "resolved_by" uuid, CONSTRAINT "PK_d4abd4fa4a7dccdb92d7dd3f175" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_resolved_by_idx" ON "merge_conflicts" ("resolved_by") `);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_conflict_type_idx" ON "merge_conflicts" ("conflict_type") `);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_status_idx" ON "merge_conflicts" ("status") `);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_token_path_idx" ON "merge_conflicts" ("token_path") `);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_token_id_idx" ON "merge_conflicts" ("token_id") `);
        await queryRunner.query(`CREATE INDEX "merge_conflicts_merge_request_id_idx" ON "merge_conflicts" ("merge_request_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "merge_conflicts_request_token_path_unique_active" ON "merge_conflicts" ("merge_request_id", "token_path") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_e5380c394ec7912046d07b54290" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_2fb8d236390c9977525fc4596ad" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_53f232a87d8aebb77ba3bece65a" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_585c8ce06628c70b70100bfb842" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_e6abd34366a5d759985d0677616" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_c62fc4ab4686bb2b90a4505760b" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_6ac06c78e5ab975acd79b1929f7" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" ADD CONSTRAINT "FK_bb370ca70b71e032fed77bceea7" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" ADD CONSTRAINT "FK_f9274539e3eaa7a5074b81a2eb5" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" ADD CONSTRAINT "FK_0cef95f1c0c2d5ad37c2b10cd63" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_versions" ADD CONSTRAINT "FK_6f57948c75c1d0b61576a07410f" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_versions" ADD CONSTRAINT "FK_a5995e3ae14e9fcf80ff471cb12" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_versions" ADD CONSTRAINT "FK_e989fc0f3b0396ccc112446dc20" FOREIGN KEY ("snapshot_id") REFERENCES "token_snapshots"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_versions" ADD CONSTRAINT "FK_0ded12e5a127af28d05a0e31811" FOREIGN KEY ("published_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_references" ADD CONSTRAINT "FK_d7d641808758fd54513d8e1c545" FOREIGN KEY ("token_id") REFERENCES "tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_references" ADD CONSTRAINT "FK_6794efd5f9948f86566ed6b174f" FOREIGN KEY ("referenced_token_id") REFERENCES "tokens"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "themes" ADD CONSTRAINT "FK_5a47a7d512bcaedd1d5c82d019f" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "themes" ADD CONSTRAINT "FK_6cc0fb5cc80daac3019ea3176c2" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "themes" ADD CONSTRAINT "FK_6581951aeb56f11d3179af522e5" FOREIGN KEY ("extends_theme_id") REFERENCES "themes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "theme_overrides" ADD CONSTRAINT "FK_f3b20c7aa5221a7eb1cfc34b64b" FOREIGN KEY ("theme_id") REFERENCES "themes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "theme_overrides" ADD CONSTRAINT "FK_80c414497d34dcdd1d6fa65f336" FOREIGN KEY ("token_id") REFERENCES "tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_memberships" ADD CONSTRAINT "FK_b917b8603c6d5c526fcdb2009de" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_memberships" ADD CONSTRAINT "FK_dd1f63903a63a80983bab747fdc" FOREIGN KEY ("membership_id") REFERENCES "memberships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_memberships" ADD CONSTRAINT "FK_37dc0b572a9a59825f62d94297a" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_fdc736f761896ccc179c823a785" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "FK_73348049217c53d971b890800d4" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "FK_2f16f71edb701c7dbe0a429f3d7" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "FK_c9a9b13e5adbae054abde7f8132" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a283bdef18876e525aefaec042f" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_0a4ace2ba56f859006688e29447" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_983d7eb19ca94bb8e343293068e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_reports" ADD CONSTRAINT "FK_2d4900602acf40ecb1a497ea862" FOREIGN KEY ("app_id") REFERENCES "apps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_reports" ADD CONSTRAINT "FK_d9eac04e0e37e3866e763436cb9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_reports" ADD CONSTRAINT "FK_be78d6a1993e846e7629f37a479" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_reports" ADD CONSTRAINT "FK_a35b184ac6365d09b8602eb2c87" FOREIGN KEY ("triggered_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_reports" ADD CONSTRAINT "FK_b5cfb3305668ff2414fbf0231a0" FOREIGN KEY ("api_key_id") REFERENCES "api_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_ab822936d927bcaa69b527d5589" FOREIGN KEY ("membership_id") REFERENCES "memberships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_7eb32f8d071861fffe502f70ac3" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_d87141b378686f82fc9eca6d39a" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_d89a34c610abac0667dbd61a34d" FOREIGN KEY ("source_environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_59158e1e52dfcb3a0a7e7dd4ff7" FOREIGN KEY ("target_environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_d3cf2c1b6dba161a8c7ad00ba60" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_bd7dff4ae96578f6d9671401145" FOREIGN KEY ("merged_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_requests" ADD CONSTRAINT "FK_3f992ae1837a503f686e56a75fa" FOREIGN KEY ("closed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" ADD CONSTRAINT "FK_28beafca17fec2790dd03b86923" FOREIGN KEY ("merge_request_id") REFERENCES "merge_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" ADD CONSTRAINT "FK_c1971bee2f776422b2907f22c39" FOREIGN KEY ("token_id") REFERENCES "tokens"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" ADD CONSTRAINT "FK_a24d97fff639d2973bcc47051e3" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" DROP CONSTRAINT "FK_a24d97fff639d2973bcc47051e3"`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" DROP CONSTRAINT "FK_c1971bee2f776422b2907f22c39"`);
        await queryRunner.query(`ALTER TABLE "merge_conflicts" DROP CONSTRAINT "FK_28beafca17fec2790dd03b86923"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_3f992ae1837a503f686e56a75fa"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_bd7dff4ae96578f6d9671401145"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_d3cf2c1b6dba161a8c7ad00ba60"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_59158e1e52dfcb3a0a7e7dd4ff7"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_d89a34c610abac0667dbd61a34d"`);
        await queryRunner.query(`ALTER TABLE "merge_requests" DROP CONSTRAINT "FK_d87141b378686f82fc9eca6d39a"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_7eb32f8d071861fffe502f70ac3"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_ab822936d927bcaa69b527d5589"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "sync_reports" DROP CONSTRAINT "FK_b5cfb3305668ff2414fbf0231a0"`);
        await queryRunner.query(`ALTER TABLE "sync_reports" DROP CONSTRAINT "FK_a35b184ac6365d09b8602eb2c87"`);
        await queryRunner.query(`ALTER TABLE "sync_reports" DROP CONSTRAINT "FK_be78d6a1993e846e7629f37a479"`);
        await queryRunner.query(`ALTER TABLE "sync_reports" DROP CONSTRAINT "FK_d9eac04e0e37e3866e763436cb9"`);
        await queryRunner.query(`ALTER TABLE "sync_reports" DROP CONSTRAINT "FK_2d4900602acf40ecb1a497ea862"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_983d7eb19ca94bb8e343293068e"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_0a4ace2ba56f859006688e29447"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a283bdef18876e525aefaec042f"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "FK_c9a9b13e5adbae054abde7f8132"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "FK_2f16f71edb701c7dbe0a429f3d7"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "FK_73348049217c53d971b890800d4"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_fdc736f761896ccc179c823a785"`);
        await queryRunner.query(`ALTER TABLE "team_memberships" DROP CONSTRAINT "FK_37dc0b572a9a59825f62d94297a"`);
        await queryRunner.query(`ALTER TABLE "team_memberships" DROP CONSTRAINT "FK_dd1f63903a63a80983bab747fdc"`);
        await queryRunner.query(`ALTER TABLE "team_memberships" DROP CONSTRAINT "FK_b917b8603c6d5c526fcdb2009de"`);
        await queryRunner.query(`ALTER TABLE "theme_overrides" DROP CONSTRAINT "FK_80c414497d34dcdd1d6fa65f336"`);
        await queryRunner.query(`ALTER TABLE "theme_overrides" DROP CONSTRAINT "FK_f3b20c7aa5221a7eb1cfc34b64b"`);
        await queryRunner.query(`ALTER TABLE "themes" DROP CONSTRAINT "FK_6581951aeb56f11d3179af522e5"`);
        await queryRunner.query(`ALTER TABLE "themes" DROP CONSTRAINT "FK_6cc0fb5cc80daac3019ea3176c2"`);
        await queryRunner.query(`ALTER TABLE "themes" DROP CONSTRAINT "FK_5a47a7d512bcaedd1d5c82d019f"`);
        await queryRunner.query(`ALTER TABLE "token_references" DROP CONSTRAINT "FK_6794efd5f9948f86566ed6b174f"`);
        await queryRunner.query(`ALTER TABLE "token_references" DROP CONSTRAINT "FK_d7d641808758fd54513d8e1c545"`);
        await queryRunner.query(`ALTER TABLE "token_versions" DROP CONSTRAINT "FK_0ded12e5a127af28d05a0e31811"`);
        await queryRunner.query(`ALTER TABLE "token_versions" DROP CONSTRAINT "FK_e989fc0f3b0396ccc112446dc20"`);
        await queryRunner.query(`ALTER TABLE "token_versions" DROP CONSTRAINT "FK_a5995e3ae14e9fcf80ff471cb12"`);
        await queryRunner.query(`ALTER TABLE "token_versions" DROP CONSTRAINT "FK_6f57948c75c1d0b61576a07410f"`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" DROP CONSTRAINT "FK_0cef95f1c0c2d5ad37c2b10cd63"`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" DROP CONSTRAINT "FK_f9274539e3eaa7a5074b81a2eb5"`);
        await queryRunner.query(`ALTER TABLE "token_snapshots" DROP CONSTRAINT "FK_bb370ca70b71e032fed77bceea7"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_6ac06c78e5ab975acd79b1929f7"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_c62fc4ab4686bb2b90a4505760b"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_e6abd34366a5d759985d0677616"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_585c8ce06628c70b70100bfb842"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_53f232a87d8aebb77ba3bece65a"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_2fb8d236390c9977525fc4596ad"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_e5380c394ec7912046d07b54290"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_request_token_path_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_merge_request_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_token_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_token_path_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_conflict_type_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_conflicts_resolved_by_idx"`);
        await queryRunner.query(`DROP TABLE "merge_conflicts"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_open_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_source_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_target_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_review_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_created_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_merged_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."merge_requests_created_at_idx"`);
        await queryRunner.query(`DROP TABLE "merge_requests"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_membership_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_team_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_role_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_member_type_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_project_membership_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."project_members_project_team_unique_active"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_app_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_trigger_source_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_triggered_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_api_key_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sync_reports_created_at_idx"`);
        await queryRunner.query(`DROP TABLE "sync_reports"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_key_hash_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_organization_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_user_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_role_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_prefix_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_created_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_last_used_at_idx"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."apps_project_environment_slug_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."apps_organization_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_platform_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_framework_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."apps_sync_status_idx"`);
        await queryRunner.query(`DROP TABLE "apps"`);
        await queryRunner.query(`DROP INDEX "public"."teams_organization_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."teams_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."teams_organization_slug_unique_active"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP INDEX "public"."team_memberships_team_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."team_memberships_membership_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."team_memberships_role_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."team_memberships_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."team_memberships_team_membership_unique_active"`);
        await queryRunner.query(`DROP TABLE "team_memberships"`);
        await queryRunner.query(`DROP INDEX "public"."theme_overrides_theme_token_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."theme_overrides_theme_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."theme_overrides_token_id_idx"`);
        await queryRunner.query(`DROP TABLE "theme_overrides"`);
        await queryRunner.query(`DROP INDEX "public"."themes_environment_slug_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."themes_one_default_per_environment"`);
        await queryRunner.query(`DROP INDEX "public"."themes_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."themes_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."themes_extends_theme_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."themes_status_idx"`);
        await queryRunner.query(`DROP TABLE "themes"`);
        await queryRunner.query(`DROP INDEX "public"."token_references_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."token_references_token_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_references_referenced_token_id_idx"`);
        await queryRunner.query(`DROP TABLE "token_references"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_environment_version_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_snapshot_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_snapshot_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_published_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_versions_published_at_idx"`);
        await queryRunner.query(`DROP TABLE "token_versions"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_environment_version_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_version_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."token_snapshots_created_by_idx"`);
        await queryRunner.query(`DROP TABLE "token_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_environment_path_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_environment_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_type_idx"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_token_kind_idx"`);
        await queryRunner.query(`DROP INDEX "public"."tokens_status_idx"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP INDEX "public"."environments_project_slug_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."environments_one_production_per_project"`);
        await queryRunner.query(`DROP INDEX "public"."environments_project_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."environments_type_idx"`);
        await queryRunner.query(`DROP INDEX "public"."environments_is_production_idx"`);
        await queryRunner.query(`DROP TABLE "environments"`);
        await queryRunner.query(`DROP INDEX "public"."projects_organization_slug_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."projects_organization_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."projects_status_idx"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP INDEX "public"."users_email_unique_active"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_organization_user_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_organization_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_user_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_role_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_status_idx"`);
        await queryRunner.query(`DROP TABLE "memberships"`);
        await queryRunner.query(`DROP INDEX "public"."roles_organization_slug_unique_active"`);
        await queryRunner.query(`DROP INDEX "public"."roles_system_slug_unique_active"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."permissions_slug_unique_active"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."organizations_slug_unique_active"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_expires_at"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

}
